inesb18/jewelry-renting-platform

.gitignore, Gemfile, Gemfile.lock, app/models/product.rb, app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20200224224557_create_active_storage_tables.active_storage.rb, db/schema.rb
Added dovent and cloudinary gems
Added 1 picture attached to User model and 1 picture attached to Product model
=> Pictures in models

app/models/product.rb, app/models/rental.rb, app/models/unavailability.rb, app/models/user.rb, db/migrate/20200224202652_create_unavailability.rb, db/schema.rb
=> Fixed unavailabilities table and added missing relationships

app/controllers/renter/products_controller.rb, app/views/renter/index.html.erb, app/views/renter/products/index.html.erb, app/views/shared/_navbar.html.erb, config/initializers/devise.rb, config/routes.rb, test/controllers/renter/products_controller_test.rb
Added the list of the users products for rent
=> Products for rent

.gitignore, app/views/renter/products/index.html.erb, db/seeds.rb
=> Add pics to product seed

app/controllers/products_controller.rb, app/views/products/index.html.erb, app/views/renter/products/index.html.erb, app/views/shared/_listproducts.html.erb
Made the list of products a partial, to use it in renter/products and products
Made the action and view for products#index
=> Index of products

app/controllers/rentals_controller.rb, app/javascript/components/total_price.js, app/javascript/packs/application.js, app/models/rental.rb, app/models/unavailability.rb, app/views/rentals/new.html.erb
Created the form and the create action for rentals
Making sure the dates are correct with models validations
Note that unavailabilities is for renter's personal unavailability. so we have to check it and also any other rentals of the product to know if the rental is possible are not.
Added some JS to dynamically display the price for the rental depending on the dates
=> Rent a product

.gitignore, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Hi guys, I fixed the styling of the dropdown menu.
=> Navbar options

app/assets/stylesheets/components/_cards.scss, app/views/owner/rentals/index.html.erb, app/views/renter/rentals/index.html.erb
=> fixed a box shadow and margin bottom for a header

app/assets/stylesheets/components/_cards.scss, app/views/shared/_listrentals.html.erb
=> Order style

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_product_divs.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_rentals.scss, app/controllers/renter/rentals_controller.rb, app/javascript/components/total_price.js, app/models/rental.rb, app/views/owner/products/index.html.erb, app/views/owner/rentals/index.html.erb, app/views/owner/rentals/show.html.erb, app/views/products/show.html.erb, app/views/rentals/new.html.erb, app/views/renter/rentals/index.html.erb, app/views/renter/rentals/show.html.erb, app/views/shared/_listproducts.html.erb, app/views/shared/_listrentals.html.erb, config/routes.rb, db/seeds.rb
Did some changes on designs
Added banners
Realigned stuff
Changed colors etc!
AND MOST IMPORTANTLY got rid of the rest of some experimentation on our db that was messing with it!
=> Polishing design

Gemfile, Gemfile.lock, app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/products/index.html.erb, config/initializers/geocoder.rb, db/migrate/20200227155633_add_coordinates_to_users.rb, db/schema.rb, package.json, yarn.lock
Address autocomplete upon signup
Longitude and lattitude added to user models and using geocode gem
=> Address autocomplete

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/users_controller.rb, app/views/shared/_navbar.html.erb, app/views/users/edit.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
User page created with ability to edit profile as well as dividing line for avatar dropdown.
=> edit user page and avatar 

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/owner/products_controller.rb, app/controllers/owner/rentals_controller.rb, app/controllers/products_controller.rb, app/controllers/rentals_controller.rb, app/controllers/renter/rentals_controller.rb, app/policies/application_policy.rb, app/policies/owner/product_policy.rb, app/policies/owner/rental_policy.rb, app/policies/product_policy.rb, app/policies/rental_policy.rb, app/policies/renter/rental_policy.rb, app/views/layouts/application.html.erb, app/views/products/_form.html.erb, app/views/products/edit.html.erb, app/views/shared/_flashes.html.erb, config/routes.rb, test/policies/owner/product_policy_test.rb, test/policies/owner/rental_policy_test.rb, test/policies/product_policy_test.rb, test/policies/rental_policy_test.rb, test/policies/renter/rental_policy_test.rb
finished pundit authorizations and edit, update, and delete for products
=> Pundit edit delete products

app/controllers/users_controller.rb, app/policies/user_policy.rb, db/schema.rb, test/policies/user_policy_test.rb
finished pundit authorization for editing and updating profile page
=> finished pundit authorization for editing and updating profile page

db/schema.rb
Keeping our master up do date with migrations (don't know why it was not pushed yet)
=> New schema with new migrations

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/product.rb, app/policies/user_policy.rb
=> finished search by keyword

app/controllers/owner/rentals_controller.rb, app/models/rental.rb, app/views/owner/rentals/index.html.erb, app/views/shared/_listrentals.html.erb, config/routes.rb, db/migrate/20200227180641_add_confirmed_to_rentals.rb, db/migrate/20200227205102_add_declined_to_rentals.rb, db/schema.rb
needs work still but working on confirm method for owners rentals
=> Work in Progress

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
styled the log in and sign up page by centering and adding a button
=> login signup style

app/assets/stylesheets/components/_cards.scss, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
added card styling for log in sign up forgot password
=> Log in sign up

app/views/shared/_listproducts.html.erb
changed the listing price to even number with no zero on end
=> changed the listing price to even number with no zero on end

app/assets/stylesheets/components/_product_divs.scss, app/views/devise/registrations/new.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb
polished style on centering text, adding flexbox for products show page and icons
=> polished style

app/controllers/products_controller.rb, app/javascript/components/near_me_unregistered.js, app/javascript/packs/application.js, app/views/products/index.html.erb
Added JS to ask for unregistered user location and display the neares…t jewels
=> Show nearest products for unregistered users

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search_bar.scss, app/controllers/products_controller.rb, app/models/product.rb, app/views/pages/home.html.erb
made progress on implementing search bar, pulling more recent changes from master to make sure everything is compatible
=> made progress on implementing search bar

app/assets/stylesheets/components/_search_bar.scss, app/views/products/index.html.erb
=> finished implementing search bars

app/controllers/owner/products_controller.rb, app/views/owner/products/index.html.erb, app/views/products/show.html.erb, app/views/rentals/new.html.erb
to add a product for an owner or rent a product for a user
=> added modals

app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/shared/_listrentals.html.erb, app/views/users/show.html.erb, config/routes.rb
forgot to create new branch, but this one was: finished being able to view user profile who is requesting rental
=> finished being able to view user profile who is requesting rental

app/controllers/products_controller.rb, app/views/products/index.html.erb, app/views/products/show.html.erb, app/views/shared/_listproducts.html.erb
Show me near me always asks for location, fixing the bug for logged in users
Also using this location to display distance from jewels on show product page
=> Fixing show near me for loged in users
